# notebu-rd2/pytest.ini
[pytest]
python_files = *test.py  # This sets the pattern for test discovery
filterwarnings =
    ignore:.*SwigPyPacked.*:DeprecationWarning
    ignore:.*SwigPyObject.*:DeprecationWarning
    ignore:.*swigvarlink.*:DeprecationWarning
